### ISSUE TITLE
Error: Exceeds 3 layers of parallel

### ISSUE THREAD

**Issue by WarriorMama777** [WarriorMama777/dify#1]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.13.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I got the error "Exceeds 3 layers of parallel".
Please identify the code part that defines this and suggest how to remove or relax this restriction.
Please suggest the most likely code part that imposes this restriction of 3.

**Comment by WarriorMama777** [comment]
下記のような手順で制限を解除できることを確認できました。
これでこのIssueは閉じます。サンキュー @dosu
文章の部分を英語に翻訳して、再出力しておいてください。
________

Difyの`Exceeds 3 layers of parallel`制限を緩和するための完全な手順を提示します。

1. まず、`api/core/workflow/graph_engine/entities/graph.py`を編集します：
```python
        # Check if it exceeds N layers of parallel
        for parallel in parallel_mapping.values():
            if parallel.parent_parallel_id:
                cls._check_exceed_parallel_limit(
                    parallel_mapping=parallel_mapping,
                    level_limit=5,  # 3から5に変更（必要に応じて調整可能）
                    parent_parallel_id=parallel.parent_parallel_id
                )
```

2. `docker/docker-compose.yaml`の`api`と`worker`サービスの設定を以下のように変更します：
```yaml
  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    restart: always
    environment:
      <<: *shared-api-worker-env
      MODE: api
    depends_on:
      - db
      - redis
    volumes:
      - ./volumes/app/storage:/app/api/storage
    networks:
      - ssrf_proxy_network
      - default

  worker:
    build:
      context: ../api
      dockerfile: Dockerfile
    restart: always
    environment:
      <<: *shared-api-worker-env
      MODE: worker
    depends_on:
      - db
      - redis
    volumes:
      - ./volumes/app/storage:/app/api/storage
    networks:
      - ssrf_proxy_network
      - default
```

3. 変更を反映させるために、以下のコマンドを順番に実行します：
```bash
# dify/dockerディレクトリに移動
cd dify/docker

# 既存のコンテナを停止
docker-compose down

# 新しいイメージをビルド（キャッシュを使用しない）
docker-compose build --no-cache api worker

# コンテナを起動
docker-compose up -d
```

注意点：
- バックアップを取ってから作業することを推奨します
- 変更前の`docker-compose.yaml`のバックアップを取っておくと安全です
- データベースやRedisのデータは`volumes`ディレクトリに保存されているので、`docker-compose down`しても失われません
- この変更はDifyの開発者が意図的に設けた制限を変更するものなので、予期せぬ影響がある可能性があります

以上の手順で、並列レイヤーの制限を3から5（または指定した値）に変更してDifyを実行できます。
